[debug] [2021-02-27T18:36:48.376Z] ----------------------------------------------------------------------
[debug] [2021-02-27T18:36:48.380Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login
[debug] [2021-02-27T18:36:48.381Z] CLI Version:   9.5.0
[debug] [2021-02-27T18:36:48.381Z] Platform:      linux
[debug] [2021-02-27T18:36:48.381Z] Node Version:  v14.16.0
[debug] [2021-02-27T18:36:48.387Z] Time:          Sat Feb 27 2021 19:36:48 GMT+0100 (Central European Standard Time)
[debug] [2021-02-27T18:36:48.387Z] ----------------------------------------------------------------------
[debug] [2021-02-27T18:36:48.387Z] 
[debug] [2021-02-27T18:36:48.394Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2021-02-27T18:36:48.979Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2021-02-27T18:36:48.980Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=856813959&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2021-02-27T18:36:59.531Z] Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[error] 
[error] Error: An unexpected error has occurred.
